// Fixed, teacher-reviewed Auckland school examples for Kiki's *practice* pepeha.
//
// Cultural safety (see docs/Pepeha_requirements.md):
//   • This data must NOT be generated by AI.
//   • Each profile is a safe practice example for Kiki — never the learner's
//     own pepeha. The selected profile controls the maunga/awa shown on later
//     pages (Find the Maunga, Find the Awa, Pepeha Board, Practise with Kiki).

export interface SchoolProfile {
  id: string
  schoolName: string
  area: string
  maunga: string
  awa: string
  // Full te reo Māori lines used on the sticker / board pages.
  maungaLine: string
  awaLine: string
}

export const SCHOOL_PROFILES: SchoolProfile[] = [
  {
    id: 'rosebank',
    schoolName: 'Rosebank School',
    area: 'Avondale, Auckland',
    maunga: 'Ōwairaka',
    awa: 'Whau',
    maungaLine: 'Ko Ōwairaka te maunga.',
    awaLine: 'Ko Whau te awa.',
  },
  {
    id: 'don-buck',
    schoolName: 'Don Buck School',
    area: 'Massey, Auckland',
    maunga: 'Pukewhakataratara',
    awa: 'Mōmutu',
    maungaLine: 'Ko Pukewhakataratara te maunga.',
    awaLine: 'Ko Mōmutu te awa.',
  },
  {
    id: 'glen-eden',
    schoolName: 'Glen Eden Primary School',
    area: 'Glen Eden, Auckland',
    maunga: 'Waikūmete',
    awa: 'Waikūmete',
    maungaLine: 'Ko Waikūmete te maunga.',
    awaLine: 'Ko Waikūmete te awa.',
  },
  {
    id: 'kauri-park',
    schoolName: 'Kauri Park School',
    area: 'Birkenhead, Auckland',
    maunga: 'Rangitoto',
    awa: 'Kahika',
    maungaLine: 'Ko Rangitoto te maunga.',
    awaLine: 'Ko Kahika te awa.',
  },
]
